// ── UI string dictionary ────────────────────────────────────────────────────
// Chrome/labels only — the long-form project copy lives alongside each
// project in data/projects.ts instead, since it's authored per-project.

import type { Lang } from "./i18n";

export const STRINGS = {
  en: {
    nav: { projects: "Projects", about: "About", interior: "Interior", visualMerch: "Visual Merchandising", contact: "Contact", talkWithUs: "Talk With Us" },
    home: {
      kicker: "Interior Design & Visual Merchandising Studio — Yogyakarta",
      weAreTitle: ["we are", "designers"] as [string, string],
      weAreBody:
        "Deui.space is an interior design and visual merchandising studio based in Yogyakarta, working across residential, commercial, and retail spaces throughout Indonesia. We believe good design is felt before it's noticed — in the weight of a material, the angle of light, the ease of moving from one room to the next.",
      portfolioLabel: "portfolio",
      viewCaseStudy: "View Case Study",
      ourProjects: ["our", "projects"] as [string, string],
      viewAll: "View All Projects",
      ctaKicker: "Personal Consultation",
      ctaTitle: ["talk", "with us"] as [string, string],
      ctaBody1: "Embark on your interior design journey with a personal consultation tailored to your unique preferences, aesthetic vision, and functional requirements.",
      ctaBody2: "Our experienced design professionals will listen attentively to your ideas, offering expert guidance and thoughtful insights to help you conceptualize and fully realize the vision for your space.",
      talkNow: "Talk Now",
      tagline: "Creating spaces that speak the language of those who inhabit them",
      exploreMore: "Explore More",
      tableProject: "Project", tableCategory: "Category", tableYear: "Year",
      hoverPreview: "Hover to preview",
    },
    projects: {
      title: "PROJECTS",
      subtitle: (n: number) => `A collection of spaces shaped by material honesty and quiet detail — ${n} projects since 2024, spanning residential, commercial, and retail work.`,
      total: "Total",
      projectCount: (n: number) => `${n} ${n === 1 ? "project" : "projects"}`,
      categories: { All: "All", Residential: "Residential", Commercial: "Commercial", Retail: "Retail" },
      showing: "Showing:",
      clear: "Clear",
      disciplineInterior: "Interior Design (Residential + Commercial)",
      disciplineVM: "Visual Merchandising (Retail)",
      viewProject: "View Project",
      noProjectsFound: "No projects found",
      loadMore: "Load More",
    },
    project: {
      category: "Category", year: "Year", location: "Location", scope: "Scope",
      specLocation: "Location", specArea: "Area", specRole: "Role", specClient: "Client",
      scopeOfWork: "Scope of Work", materialsUsed: "Materials Used", visualization: "Visualization", status: "Status",
      theBrief: "The Brief", theApproach: "The Approach",
      gallery: "Gallery", clickToExpand: "Click to expand", expand: "Expand", visualCredit: "All 3D visualization © Deui.space",
      upNext: "Up Next", nextProject: "Next Project", viewAllProjects: "View All Projects", projectDetails: "Project Details",
    },
    about: {
      kicker: "About",
      title: ["hi, i'm", "fannisa"] as [string, string],
      role: "Interior Design & Visual Merchandising",
      introTitle: "About Me",
      introBody:
        "I'm an Architecture graduate from Universitas Atma Jaya Yogyakarta (2025), based in Yogyakarta, Indonesia. I have a strong interest in interior design and visual merchandising, with hands-on experience across several interior practices, and I currently run a freelance interior design business at Deui.space. I work across concept design, space planning, detailing, and design visualization using SketchUp, AutoCAD, Enscape, and V-Ray — comfortable working independently or in a team, communicative, and always looking to learn.",
      skillsTitle: "Skills & Tools",
      drafting: "Drafting & Modelling", graphics: "Graphics", softSkills: "Soft Skills", language: "Language",
      draftingItems: ["AutoCAD", "SketchUp", "Enscape", "V-Ray"],
      graphicsItems: ["Canva", "Adobe InDesign", "Adobe Photoshop", "Adobe Premiere"],
      softSkillsItems: ["Teamwork", "Honesty", "Problem Solving", "Responsibility", "High Motivation"],
      languageItems: ["English — Intermediate"],
      educationTitle: "Education",
      educationDegree: "S1 Architecture",
      educationSchool: "Universitas Atma Jaya Yogyakarta",
      educationYears: "2021 – 2025",
      experienceTitle: "Professional Experience",
      experiences: [
        { year: "2025", role: "Freelance", company: "PlayWorks", description: "Designed PlayWorks store interiors, both standard unit and island formats, and designed pop-up stores for POSM." },
        { year: "2025", role: "Freelance", company: "Lab House", description: "Designed a commercial perfume lab across two branches in Yogyakarta — Seturan and Jalan Kaliurang." },
        { year: "2024", role: "Internship", company: "Stara Design", description: "Designed a safe, functional classroom space for toddlers aged 2–3 years." },
        { year: "2024", role: "Internship", company: "Griya Prima Andalan", description: "Designed residential interiors — boarding houses (kost), pavilions, and offices." },
        { year: "2023", role: "Freelance", company: "Tanpa Jarak Office", description: "Designed a two-storey office interior and a small restaurant next to the office." },
      ],
      academicTitle: "Academic Experience",
      academicExperiences: [
        { year: "2023 – 2024", role: "Design & Documentation Team", org: "Sepekan Arsitektur", description: "Designed posters and flyers, ran the event photo booth, and designed committee certificates." },
        { year: "2022", role: "Design & Documentation Team", org: "Wanaprasta", description: "Documented the event and designed committee certificates." },
      ],
      awardsTitle: "Awards & Achievements",
      awards: [
        { title: "PADC 280", description: "Top 100 Platinum Finalist, Architectural Design Competition", year: "2023" },
        { title: "Borobudur Youth Engage Camp (UNESCO)", description: "Advanced to the top 15 proposals and continued to the bootcamp in Borobudur", year: "2024" },
      ],
      downloadCV: "Download CV",
      contactTitle: "Get in Touch",
    },
    footer: {
      services: "Services", studio: "Studio", follow: "Follow",
      tagline: ["Spaces designed with intention.", "Environments built to endure."] as [string, string],
      serviceItems: ["Interior Design", "Visual Merchandising", "Space Planning", "POSM Design"],
      studioItems: { projects: "Projects", about: "About", contact: "Contact" },
      rights: "All rights reserved.",
    },
  },
  id: {
    nav: { projects: "Proyek", about: "Tentang", interior: "Interior", visualMerch: "Visual Merchandising", contact: "Kontak", talkWithUs: "Hubungi Kami" },
    home: {
      kicker: "Studio Desain Interior & Visual Merchandising — Yogyakarta",
      weAreTitle: ["kami", "desainer"] as [string, string],
      weAreBody:
        "Deui.space adalah studio desain interior dan visual merchandising yang berbasis di Yogyakarta, mengerjakan ruang residensial, komersial, dan retail di seluruh Indonesia. Kami percaya desain yang baik terasa sebelum disadari — pada bobot sebuah material, sudut jatuhnya cahaya, kemudahan berpindah dari satu ruang ke ruang lain.",
      portfolioLabel: "portofolio",
      viewCaseStudy: "Lihat Studi Kasus",
      ourProjects: ["proyek", "kami"] as [string, string],
      viewAll: "Lihat Semua Proyek",
      ctaKicker: "Konsultasi Personal",
      ctaTitle: ["hubungi", "kami"] as [string, string],
      ctaBody1: "Mulailah perjalanan desain interior Anda melalui sesi konsultasi personal yang dirancang khusus untuk memahami preferensi, gaya, dan kebutuhan unik ruang Anda.",
      ctaBody2: "Tim desainer berpengalaman kami siap mendengarkan ide-ide Anda dengan saksama, memberikan panduan ahli, serta wawasan mendalam untuk mewujudkan ruang impian Anda.",
      talkNow: "Hubungi Sekarang",
      tagline: "Menciptakan ruang yang berbicara dalam bahasa penghuninya",
      exploreMore: "Jelajahi Semua",
      tableProject: "Proyek", tableCategory: "Kategori", tableYear: "Tahun",
      hoverPreview: "Arahkan kursor untuk pratinjau",
    },
    projects: {
      title: "PROYEK",
      subtitle: (n: number) => `Kumpulan ruang yang dibentuk oleh kejujuran material dan detail yang tenang — ${n} proyek sejak 2024, mencakup pekerjaan residensial, komersial, dan retail.`,
      total: "Total",
      projectCount: (n: number) => `${n} proyek`,
      categories: { All: "Semua", Residential: "Residensial", Commercial: "Komersial", Retail: "Ritel" },
      showing: "Menampilkan:",
      clear: "Hapus filter",
      disciplineInterior: "Desain Interior (Residensial + Komersial)",
      disciplineVM: "Visual Merchandising (Ritel)",
      viewProject: "Lihat Proyek",
      noProjectsFound: "Tidak ada proyek ditemukan",
      loadMore: "Muat Lebih Banyak",
    },
    project: {
      category: "Kategori", year: "Tahun", location: "Lokasi", scope: "Lingkup",
      specLocation: "Lokasi", specArea: "Luas", specRole: "Peran", specClient: "Klien",
      scopeOfWork: "Lingkup Kerja", materialsUsed: "Material yang Digunakan", visualization: "Visualisasi", status: "Status",
      theBrief: "Kebutuhan", theApproach: "Pendekatan",
      gallery: "Galeri", clickToExpand: "Klik untuk memperbesar", expand: "Perbesar", visualCredit: "Seluruh visualisasi 3D © Deui.space",
      upNext: "Selanjutnya", nextProject: "Proyek Berikutnya", viewAllProjects: "Lihat Semua Proyek", projectDetails: "Detail Proyek",
    },
    about: {
      kicker: "Tentang",
      title: ["hai, saya", "fannisa"] as [string, string],
      role: "Desain Interior & Visual Merchandising",
      introTitle: "Tentang Saya",
      introBody:
        "Saya merupakan lulusan Arsitektur Universitas Atma Jaya Yogyakarta (2025) dengan masa studi 3,8 tahun, dan berdomisili di Yogyakarta. Memiliki minat kuat pada desain interior dan visual merchandiser. Berpengalaman dalam kerja praktik interior di beberapa perusahaan serta saat ini mengembangkan bisnis interior freelance di @Deui.space. Menguasai perancangan konsep, layout ruang, detailing, dan visualisasi desain menggunakan SketchUp, AutoCAD, Enscape, dan V-Ray. Terbiasa bekerja mandiri maupun dalam tim, komunikatif, ingin belajar dan adaptif.",
      skillsTitle: "Skill & Tools",
      drafting: "Drafting & Modelling", graphics: "Grafis", softSkills: "Soft Skills", language: "Bahasa",
      draftingItems: ["AutoCAD", "SketchUp", "Enscape", "V-Ray"],
      graphicsItems: ["Canva", "Adobe InDesign", "Adobe Photoshop", "Adobe Premiere"],
      softSkillsItems: ["Mampu Bekerja dalam Tim", "Jujur", "Problem Solving", "Bertanggung Jawab", "Semangat Tinggi"],
      languageItems: ["Bahasa Inggris — Intermediate"],
      educationTitle: "Pendidikan",
      educationDegree: "S1 Arsitektur",
      educationSchool: "Universitas Atma Jaya Yogyakarta",
      educationYears: "2021 – 2025",
      experienceTitle: "Pengalaman Profesional",
      experiences: [
        { year: "2025", role: "Freelance", company: "PlayWorks", description: "Merancang interior store Playworks baik unit maupun island, dan merancang pop up store untuk POSM." },
        { year: "2025", role: "Freelance", company: "Lab House", description: "Merancang lab parfum komersil di 2 cabang di Yogyakarta, yaitu Seturan dan Jalan Kaliurang." },
        { year: "2024", role: "Intern", company: "Stara Design", description: "Merancang ruang kelas yang aman dan fungsional dengan target pengguna balita usia 2–3 tahun." },
        { year: "2024", role: "Intern", company: "Griya Prima Andalan", description: "Merancang interior residensial — kost, pavilliun, dan perkantoran." },
        { year: "2023", role: "Freelance", company: "Tanpa Jarak Office", description: "Merancang interior kantor 2 lantai dan rumah makan sederhana tepat di samping kantor." },
      ],
      academicTitle: "Pengalaman Akademik",
      academicExperiences: [
        { year: "2023 – 2024", role: "Tim Desain dan Dokumentasi", org: "Sepekan Arsitektur", description: "Merancang poster dan flyer, menjaga dan mengoperasikan photo booth, serta mendesain sertifikat panitia." },
        { year: "2022", role: "Tim Desain dan Dokumentasi", org: "Wanaprasta", description: "Mendokumentasikan acara dan mendesain sertifikat panitia." },
      ],
      awardsTitle: "Penghargaan & Pencapaian",
      awards: [
        { title: "PADC 280", description: "Finalis 100 Besar Platinum, Architectural Design Competition", year: "2023" },
        { title: "Borobudur Youth Engage Camp (UNESCO)", description: "Lolos 15 besar proposal dan lanjut bootcamp di Borobudur", year: "2024" },
      ],
      downloadCV: "Unduh CV",
      contactTitle: "Hubungi Saya",
    },
    footer: {
      services: "Layanan", studio: "Studio", follow: "Ikuti",
      tagline: ["Ruang yang dirancang dengan penuh intensi.", "Lingkungan yang dibangun untuk bertahan lama."] as [string, string],
      serviceItems: ["Desain Interior", "Visual Merchandising", "Perencanaan Ruang", "Desain POSM"],
      studioItems: { projects: "Proyek", about: "Tentang", contact: "Kontak" },
      rights: "Seluruh hak cipta dilindungi.",
    },
  },
} satisfies Record<Lang, unknown>;

export function useStrings(lang: Lang) {
  return STRINGS[lang];
}
